### ISSUE TITLE
Support for multiple LaTex in TableView (Ex : Each cell has its own LaTex)

### ISSUE THREAD

**Issue by ankit0812** [TeamSlader/iOSLaTeX#4]
Can anyone help me with using this in UITableViewCell's ? I get a flickr and then proper render, some issues with the height also.

**Comment by shujew** [comment]
@ankit0812 Can you elaborate on the flickr? Where does it occur? Background or inside cell? Can you also post some example code?

**Comment by ankit0812** [comment]
Please find the code in this repo. Please help me out. A fork or anything would be great. 
can also ping me on ankitkumargupta0812@gmail.com

**Comment by shujew** [comment]
The flickering issue is caused because the UITableViewCell's backgroundColor is not set. It is fixed if you change line 26 in LatexQuestionTableViewCell to
`self.imageView1.backgroundColorWhileRenderingLaTeX = UIColor.white`

**Comment by shujew** [comment]
To achieve resizing in your example project, I
- changed the image content mode to aspect fit
- removed the 78.5 height constraint on the image view inside
- reloaded the cell after latex was rendered
```
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "LatexQuestionTableViewCell") as! LatexQuestionTableViewCell
        let latexStringLocal = latexString.replacingOccurrences(of: "2", with: "\(indexPath.row)")
        if cell.isFirstTime  {
            cell.isFirstTime = false
            cell.imageView1.render(latexStringLocal, shouldResize: true) { (error) in
                if let error = error {
                    print("\(error)")
                    return
                }
                tableView.reloadRows(at: [indexPath], with: .fade)
                print("Successfully rendered LaTeX")
            }
        }
        return cell
    }
```

**Comment by shujew** [comment]
The implementation above has some ui glitches before it resizes it + there are extra margins. In the Slader app, I achieved the result cleanly with no glitches
- I don't use a LaTeXImageView inside a UITableViewCell
- I have 1 global LaTeXRenderer which converts all LaTeX to plain images, then appends them to the UITableView's datasource
- After LaTeXRenderer adds one image, I simply insert a row in my UITableView

Please open a new issue if you find any other potential bugs. Thanks

**Comment by dverma4u** [comment]
@shujew I'm also rendering latex in uicollectionview cells But the problem i am facing is that the same latex is showing again and again in every cell. Can you help me in resolving this issue with iOSLaTeX?

**Comment by KaleemullahPatel** [comment]
> To achieve resizing in your example project, I
> 
> * changed the image content mode to aspect fit
> * removed the 78.5 height constraint on the image view inside
> * reloaded the cell after latex was rendered
> 
> ```
> func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
>         let cell = tableView.dequeueReusableCell(withIdentifier: "LatexQuestionTableViewCell") as! LatexQuestionTableViewCell
>         let latexStringLocal = latexString.replacingOccurrences(of: "2", with: "\(indexPath.row)")
>         if cell.isFirstTime  {
>             cell.isFirstTime = false
>             cell.imageView1.render(latexStringLocal, shouldResize: true) { (error) in
>                 if let error = error {
>                     print("\(error)")
>                     return
>                 }
>                 tableView.reloadRows(at: [indexPath], with: .fade)
>                 print("Successfully rendered LaTeX")
>             }
>         }
>         return cell
>     }
> ```

Above code resolved my problem, Thanks for this awesome lib
