### ISSUE TITLE
Unable to apply font size on the latex string

### ISSUE THREAD

**Issue by KaleemullahPatel** [TeamSlader/iOSLaTeX#6]
I am trying to use larger font size on the latex string, but I think some function in library is overriding this functionality.

**Comment by shujew** [comment]
@KaleemullahPatel Unfortunately, that feature is not yet supported. If you wish to hardcode your font size or add this functionality, you should be looking at https://github.com/TeamSlader/iOSLaTeX/blob/master/iOSLaTeX/Assets/MathJaxRenderer.html

**Comment by KaleemullahPatel** [comment]
Can you please guide me in all this script how can I update the font size, as I have attempted to do so without success. It will be of great help if you can guide me more with this issue.
