### ISSUE TITLE
LaTeXImageView inside UICollectionViewCell

### ISSUE THREAD

**Issue by dverma4u** [TeamSlader/iOSLaTeX#7]
i am rendering using LaTeXImageView inside UICollectionViewCell. But the problem i am facing is that the same latex is showing again and again in every cell. Also the performance is not that good it flicker 4 -5 times before displaying my final result. how to solve this issues?

**Comment by shujew** [comment]
Hi @dverma4u,
LaTeXImageView is known to have issues inside UITableViewCell and UICollectionViewCell. Alternatively, 
- create a LaTeXRenderer to be used for the whole view controller
- use LaTeXRenderer to generate your LaTeX images 
- Display the LaTeX images through a UIImageView inside UICollectionViewCell

**Comment by dverma4u** [comment]
hi @shujew thanks for response. Can you please explain 2nd step of generating latex images? Or can you please share one Little demo/example to help me understand how to solve this issue

**Comment by shujew** [comment]
@dverma4u Try out the code below. I have not tested this.

First declare a global LaTeXRenderer object
```swift
var laTeXRenderer: LaTeXRenderer!
    
override func viewDidLoad() {
    super.viewDidLoad()

    laTeXRenderer = LaTeXRenderer(parentView: self.view)
}
```

Render LaTeX whenever inside cell on demand
```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let cell = tableView.dequeueReusableCell(withIdentifier: "CustomCell", for: indexPath) as! CustomTableViewCell
        
    laTeXRenderer.render(answerText) { (renderedLaTeX, error) in
        // renderedLaTeX is a UIImage here. Treat it like you would any other UIImage
        cell.renderedLaTeX = renderedLaTeX
    }

    return cell
}
```

Note: If your app gets sluggish because you're rendering so much LaTeX, I recommend preloading all LaTeX before displaying any content in your UITableView

**Comment by dverma4u** [comment]
@shujew  Thanks for explaining. Your solution helped a little now image appears correctly once but 
The only problem i am facing now is that my ```UIImageView```  is loading again and again because of reusable cells. Any guess how can i fix that?

**Comment by shujew** [comment]
@dverma4u 

Inside your UITableViewCell, try something like this

```swift
override func prepareForReuse() {
    self.imageView.image = nil
}
```

**Comment by dverma4u** [comment]
@shujew thank you for response, i tried but it didn't worked now the application is crashing saying unexpected found nil while unwrapping options pointing latexRenderer. 
Also how can i set height constraints now like i used to do with LatexImageView?

**Comment by shujew** [comment]
@dverma4u Weird. I can't see your code so unsure why but I'll try to add an example for what you're trying to achieve in the current codebase.

As for font size, that's a feature that I haven't added yet.

**Comment by shujew** [comment]
@dverma4u Please see iOSLaTeX/Example/iOSLaTeX/Controllers/TableExampleViewController.swift

**Comment by dverma4u** [comment]
@shujew yes, Now performance is really improved. Thanks.

**Comment by dverma4u** [comment]
@shujew another major problem causing application crash if we goBack while LaTeX is being rendered.

Application Crashes at ```self.hidingView = UIView(frame: self.parentView.bounds)``` of ```LaTeXRenderer``` saying ```Unexpectedly found nil while unwrapping an Optional value```

**Comment by shujew** [comment]
@dverma4u Please create a new issue for this bug.
